/*
Inspired by https://dribbble.com/shots/2004657-Alarm-Clock-concept
 */

class Clock{

  constructor(data){
    this.data = data
    this.play_symbol = "►"
    this.pause_symbol = "▌▌"
    this.is_playing = false;
    this.index = 0;
    $('button#start_button').click(() => {
      if (this.is_playing == true){
        this.stop_animation();
        this.is_playing = false;
      }else{
        this.is_playing = true;
        $('#start_button').text(this.pause_symbol);

        this.index = 0;
        this.intervalLoop();
        this.interval = setInterval(() => {
            this.intervalLoop();
        }, 2000);
      }
  	});

    this.slider = new rSlider({
      target: '#time_range',
      values: this.data.map((x) => x["time"]),
      range: true,
      tooltip: false,
      scale: true,
      labels: true,
      onChange: function (vals) {
        let ids = [];
        let times = data.map((x) => x.time);
        let v = vals.split(",")
        let sliced_data = data.slice(times.indexOf(v[0]), 1+times.indexOf(v[1]))
        sliced_data.forEach((x) => ids.push(...x.ids))
        heatmap.show_roads_with_ids(ids)
      }
    });

  }

  intervalLoop(){
    this.setCaptions(this.data[this.index].time)

    this.index++;
    if(this.index > this.data.length-1){
      this.stop_animation();
    }
  }

  stop_animation(){
    $('#start_button').text(this.play_symbol);
    clearInterval(this.interval);
  }

  setCaptions(time) {
    this.slider.setValues(time, time)
  };

}


// ---
// generated by coffee-script 1.9.2
